= DML

** 데이터베이스의 데이터 조회, 검색, 변형

** 관계 대수 및 투플 관계 해석에 기반

** 투플 삽입, 삭제, 수정

---

----
입력:
SELECT DISTINCT PilotName, Age
FROM Pilot P
WHERE P.Age <= 40;
----

----
출력:

----

==== SELECT

* 관계 대수에서 프로젝션(Projection-π)연산과 일치, 결과에 나타날 속성을 나열할때 사용

----
SELECT [DISTINCT] A1, A2, ....., An

ex) SELECT DISTINCT PilotName, Age
----

** 형식 질의 언어는 릴레이션의 집합이라는 개념을 기반

*** 중복된 투플은 릴레이션에 나타날 수 없음
*** 중복성 제거는 시간 소비, SQL은 프로젝션, 릴레이션에서도 중복을 허용
*** 중복이 없어야 하는경우 DISTINCT 키워드 사용
*** all키워드를 사용하여 중복 허용(이게 기본)

** From리스트에 나오는 테이블들로부터 산출된 필드 이름들의 리스트

*** ex) 위에 예시로, Pilot 릴레이션에 P에서 PilotName과 Age를 출력

** 상수나 투플들의 속성에 적용되는ㄷ +, -, *, /등, 산술적 표현 가능

** 데이터 타입에 맞게 산술 연산 허용

** SELECT절의 속성 목록은 일반적인 형태 (AS구문 이용)


** AS함수
----
입력

SELECT PassengerName AS 승객이름
FROM Passenger;
----

----
결과

+--------------+
| 승객이름     |
+--------------+
| 홍길동       |
| 이순신       |
| 안중근       |
| 김영랑       |
| 김소월       |
| 윤동주       |
| 천상병       |
+--------------+

----

** SUM함수

----
입력

SELECT SUM(Age)
FROM Passenger;
----

----
출력

+----------+
| SUM(Age) |
+----------+
|      268 |
+----------+
----

** AVG함수
----
입력

SELECT AVG(Age)
FROM Passenger;
----

----
출력

+----------+
| AVG(Age) |
+----------+
|  44.6667 |
+----------+
----



---


==== FROM

* 관계 대수의 카티션 프로덕트에 해당함, 조회할 릴레이션 나열

** FROM에 리스트는 질의에 대한 결과 생성을 위해 참여하는 목록

** 범위 변수 사용하여, 릴레이션의 별칭 정의

** 리스트의 카디션 프러덕트 정의

*** 자연 조인은 프러덕드, 셀렉션 연산, 프로젝션 연산으로 수션

*** 간단히 자연 조인을 SQL연산으로 표현 가능

** 하나 이상의 릴레이션 스키마에서 나타나는 속성의 모호성을 피하기 위해 relation-name.attribute.com표기법 사용

** FROM절에서 외부 조인을 수행할 수 있는 확장을 포함

* ex) 운항에 참여하는 모든 비행기의 종류와 항공사, 운항 날짜를 구하라

대수식 = π KindOfAircraft, Airline, FlightDate(Aircraft ⋈ Flight)

----
입력

SELECT KindOfAircraft, Airline, FlightDate
From Aircraft AS A JOIN Flight AS F ON A,AircraftNo = F,AricraftNo;
----

----
출력

+----------------+---------------------+---------------------+
| KindOfAircraft | Airline             | FlightDate          |
+----------------+---------------------+---------------------+
| Boeing 747     | 대한항공            | 2022-10-23 10:20:00 |
| Boeing 747     | 대한항공            | 2022-10-26 13:00:00 |
| Boeing 747     | 대한항공            | 2022-11-15 10:00:00 |
| Airbus A380    | 아시아나 항공       | 2022-12-01 18:00:00 |
| Airbus A380    | 아시아나 항공       | 2022-12-10 10:00:00 |
| Airbus A300    | 대한항공            | 2022-11-13 11:00:00 |
| Boeing 737-800 | 제주항공            | 2022-11-23 09:00:00 |
| Boeing 737-800 | 제주항공            | 2022-11-12 17:30:00 |
+----------------+---------------------+---------------------+

----


----
FROM r1, r2, .... rn

ex) FROM Pilot P
----

---
==== WHERE
* 관계대수에서 셀렉션(Selection - σ) 연산과 일치함
----
WHERE p

// "나이가 40세 이하인 승객의 이름과 나이를 구하라"
ex) WHERE P.Age <= 40

----

* π PassengerName, Age(σAge>=40(Passenger))(관계 대수식) -> { S.PassengerName, S.Age | ∃S ∈ Passenger ∧ S.Age >= 40)} (투플 관계 해석)

* FROM 절에 나타나는 릴레이션 속성들의 조건

* WHERE 절의 조건식으로 연산 수행

** 식 op 식 형태의 조건들을 조합으로, op는 boolean 연산자 중에 하나

** 범위 연산을 위해 BETWEEN 연산 제공

*** 연산은 필드이름, 상수, 산술/문자열중 하나

* 번호가 101인 비행기 운항 일자를 구하라

πFlightDate(σAircraftNo=101(Aircraft ⋈ Flight)
----
입력

SELECT FlightDate
FROM Aircraft AS A INNER JOIN Flight AS F On A.aircraftNo = F.AricraftNo
WHERE A.AircraftNo = 101;
----

----
출력

+---------------------+
| FlightDate          |
+---------------------+
| 2022-10-23 10:20:00 |
| 2022-10-26 13:00:00 |
| 2022-11-15 10:00:00 |
+---------------------+
----


---

NOTE: SELECT PassengerName, Grade + 1, Age
FROM Passenger

* 해당 문장을 사용해도, 데이터베이스 내부에 값 자체는 변하지 않는다. 단지, 출력만 그렇게 할 뿐
